### PR TITLE
Fix if localstorage has no values

### PR DESCRIPTION
**Pull request by pgdaniel**
Next up tutorial

### CODE REVIEW

**Comment by patbenatar** [comment]
:+1: Baws! Thanks

**Comment by patbenatar** [comment]
Side note: I love your branch naming :pineapple:

**Comment by patbenatar** [comment]
@pgdaniel Deployed to http://notational-momentum-prod.herokuapp.com and working for new users!

**Comment by pgdaniel** [comment]
@patbenatar Thanks!

**Pull request merged**
